- name: Packages | Install
  tags:
    - packages
    - phase1
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    # drupal
    - php5
    - php5-apcu
    - php5-cgi
    - php5-cli
    - php5-curl
    - php5-dev
    - php5-fpm
    - php5-gd
    - php5-mysql
    - php-pear

- name: Packages | run php-fpm
  service: name=php5-fpm state=started

- name: Packages | php conf
  tags:
    - phase1
    - packages
  copy: src=etc/php5/fpm/{{ item }} dest=/etc/php5/fpm/{{ item }}
  with_items:
    - php-fpm.conf
    - php.ini
    - pool.d/www.conf
  notify: restart php-fpm

- name: Package | nginx mcgillcycling config
  tags:
    - phase1
    - packages
  copy: src=etc/nginx/sites-available/mcgillcycling dest=/etc/nginx/sites-available/mcgillcycling
  notify: restart nginx

- name: Package | nginx enable mcgillcycling
  tags:
    - phase1
    - packages
  file: state=link src=/etc/nginx/sites-available/mcgillcycling dest=/etc/nginx/sites-enabled/mcgillcycling
  notify: restart nginx
