- name: mct | user | Create mct
  tags:
    - phase1
  user: name=mct comment="McGill Cycling Team"
        system=True shell=/bin/bash
        append=yes generate_ssh_key=yes

- name: mct | user | home folder permissions
  tags:
    - phase1
  file: dest=/home/mct mode=755 state=directory

- name: mct | user | install dotfiles
  tags:
    - phase2
  file: state=link src=/usr/local/lib/dotfiles/{{ item }} dest=.{{ item }}
  with_items:
    - emacs
    - bashrc
  register: result
  ignore_errors: True
  sudo: True
  sudo_user: mct

# catch original bashrc and remove it
- name: mct | user | remove default bashrc
  tags:
    - phase2
  file: state=absent path=.bashrc
  when: result|failed
  sudo: True
  sudo_user: mct

- name: mct | user | install dotfiles
  tags:
    - phase2
  file: state=link src=/usr/local/lib/dotfiles/{{ item }} dest=.{{ item }}
  with_items:
    - emacs
    - bashrc
  when: result|failed
  sudo: True
  sudo_user: mct
