- name: mct | user | Create mct
  tags:
    - phase1
  user: name=mct comment="McGill Cycling Team"
        group=mct system=True
        append=yes generate_ssh_key=yes

- name: mct | user | authorised keys
  tags:
    - phase1
  copy: src=home/mct/ssh/authorized_keys
        dest=home/mct/ssh/authorized_keys 
        mode=600
  sudo_user: mct

- name: mct | user | home folder permissions
  tags:
    - phase1
  file: dest=/home/mct mode=755 state=directory
  sudo_user: mct

- name: mct | user | install dotfiles
  tags:
    - phase1
  file: type=link src=/usr/local/lib/dotfiles/{{ item }} dest={{ item }}
  with_items:
    - emacs
    - bashrc
  sudo_user: mct
