tasks:
  - name: mct | website | public_html folder
    file: dest=/home/mct/public_html mode=755 type=directory
    user: mct

  - name: mct | website | mcgillcycling code
    git: repo=git@bitbucket.org:jonvk/mcgillcycling.git
         dest=/home/mct/mcgillcycling version=2013-05-28
    user: mct

  - name: mct | website | mcgillcycling .../files permissions
    file: type=file src=/home/mct/mcgillcycling/site/sites/default/files group:www-data mode=775
    user: mct

  - name: mct | website | mcgillcycling symlink
    file: type=link src=/home/mct/mcgillcycling/site dest=/home/mct/public_html/
    user: mct

