- name: mct | website | public_html folder
  tags:
    - phase1
  file: dest=public_html mode=755 state=directory
  sudo: True
  sudo_user: mct

- name: mct | website | mcgillcycling code
  tags:
    - phase2
    - mct
  git: repo=git@bitbucket.org:jonvk/mcgillcycling.git
       dest=mcgillcycling version=prod-2014-06-25-2
  sudo: True
  sudo_user: mct

- name: mct | website | mcgillcycling site/.../files permissions
  tags:
    - phase2
  file: state=directory path=mcgillcycling/site/sites/default/files owner=mct group=www-data mode=775 recurse=True

- name: mct | website | mcgillcycling symlink
  tags:
    - phase2
  file: state=link src=/home/mct/mcgillcycling/site dest=public_html/mcgillcycling
  sudo: True
  sudo_user: mct

