- name: mct | website | public_html folder
  tags:
    - phase1
  file: dest=/home/mct/public_html mode=755 state=directory
  sudo_user: mct

- name: mct | website | mcgillcycling code
  tags:
    - phase2
  git: repo=git@bitbucket.org:jonvk/mcgillcycling.git
       dest=/home/mct/mcgillcycling version=2013-05-28
  sudo_user: mct

- name: mct | website | mcgillcycling site/.../files permissions
  tags:
    - phase2
  file: type=file src=/home/mct/mcgillcycling/site/sites/default/files group:www-data mode=775
  sudo_user: mct

- name: mct | website | mcgillcycling symlink
  tags:
    - phase2
  file: state=link src=/home/mct/mcgillcycling/site dest=/home/mct/public_html/
  sudo_user: mct

