- name: User | Create jonathan
  tags:
    - phase1
  user: name="jonathan" comment="Jonathan Villemaire-Krajden"
        groups="admin,www-data" shell=/bin/bash
        append=yes generate_ssh_key=yes

- name: User | jonathan | authorised keys
  tags:
    - phase1
  copy: src=home/jonathan/ssh/authorized_keys
        dest=.ssh/authorized_keys 
        mode=600
  sudo: True
  sudo_user: jonathan

- name: User | jonathan | projects folder
  tags:
    - phase1
  file: dest=projects state=directory
  sudo: True
  sudo_user: jonathan

- name: User | jonathan | virtualenv folder
  tags:
    - phase1
  file: dest=virtualenv mode=700 state=directory
  sudo: True
  sudo_user: jonathan

- name: User | jonathan | dotfiles
  tags:
    - phase2
  git: repo=https://github.com/odontomachus/dotfiles.git
       dest=projects/dotfiles version=linode
  sudo: True
  sudo_user: jonathan

- name: User | jonathan | install dotfiles
  tags:
    - phase2
  file: state=link src=projects/dotfiles/{{ item }} dest=.{{ item }}
  with_items:
    - emacs
    - bashrc
  register: result
  sudo: True
  sudo_user: jonathan

# catch original bashrc and remove it
- name: User | jonathan | remove default bashrc
  tags:
    - phase2
  file: state=absent path=.bashrc
  when: result|failed
  sudo: True
  sudo_user: jonathan

- name: User | jonathan | install dotfiles
  tags:
    - phase2
  file: state=link src=projects/dotfiles/{{ item }} dest=.{{ item }}
  with_items:
    - emacs
    - bashrc
  when: result|failed
  sudo: True
  sudo_user: jonathan