---
- name: jvk | user | Create jvk
  tags:
    - phase1
  user: name=jvk comment="j-vk.com"
        system=True shell=/bin/bash
        append=yes generate_ssh_key=yes

- name: jvk | user | home folder permissions
  tags:
    - phase1
  file: dest=/home/jvk mode=755 state=directory

- name: jvk | user | virtualenv folder
  tags:
    - phase1
  file: dest=/home/jvk/virtualenv mode=770 state=directory
  sudo: True
  sudo_user: jvk

- name: jvk | user | install dotfiles
  tags:
    - phase1
  file: state=link src=/usr/local/lib/dotfiles/{{ item }} path=.{{ item }}
  with_items:
    - emacs
    - bashrc
  register: result
  sudo: True
  sudo_user: jvk

# catch original bashrc and remove it
- name: jvk | user | remove default bashrc
  tags:
    - phase2
  file: state=absent path=.bashrc
  when: result|failed
  sudo: True
  sudo_user: jvk

- name: jvk | user | install dotfiles
  tags:
    - phase2
  file: state=link src=/usr/local/lib/dotfiles/{{ item }} dest=.{{ item }}
  with_items:
    - emacs
    - bashrc
  when: result|failed
  sudo: True
  sudo_user: jvk


- name: jvk | website src
  tags:
    - phase2
  git: repo=git@bitbucket.org:jonvk/jvk.git
       dest=jvk version=stable
  sudo: True
  sudo_user: jvk
