- name: files.j-vk.com | directory
  tags:
    - phase1
  file: state=directory dest=/var/www/files owner=jonathan group=www-data
        mode=0755

- name: files.j-vk.com | nginx config
  tags:
    - phase1
  copy: src=etc/nginx/sites-available/files dest=/etc/nginx/sites-available/files
  notify: reload nginx

- name: files.j-vk.com  | nginx enable
  tags:
    - phase1
  file: state=link src=/etc/nginx/sites-available/files
        dest=/etc/nginx/sites-enabled/files
  notify: reload nginx
